version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbit_mq
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - cnd_rabbitmq_data:/var/lib/rabbitmq/
    - cnd_rabbitmq_log:/var/log/rabbitmq/
    networks:
      - cnd_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
      - cnd_mongodb_data:/data/db
    networks:
      - cnd_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  drawing_service:
    build:
      context: ../drawing_service
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    networks:
    - cnd_network
    environment:
      - RABBIT_INIT_ROOT_USERNAME=${RABBIT_INIT_ROOT_USERNAME}
      - RABBIT_INIT_ROOT_PASSWORD=${RABBIT_INIT_ROOT_PASSWORD}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_HOST=${RABBIT_HOST}
      - QUEUE_DRAWING_EVENT=${QUEUE_DRAWING_EVENT}
      - DRAW_MESSAGE_EXCHANGE=${DRAW_MESSAGE_EXCHANGE}

  customer_service:
    build:
      context: ../customer_service
      dockerfile: Dockerfile
    ports:
    - "8085:8080"
    networks:
      - cnd_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBIT_INIT_ROOT_USERNAME=${RABBIT_INIT_ROOT_USERNAME}
      - RABBIT_INIT_ROOT_PASSWORD=${RABBIT_INIT_ROOT_PASSWORD}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_HOST=${RABBIT_HOST}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_HOST=${MONGO_HOST}
      - QUEUE_DRAWING_EVENT=${QUEUE_DRAWING_EVENT}
      - CUSTOMER_COLLECTION_NAME=${CUSTOMER_COLLECTION_NAME}

volumes:
  cnd_rabbitmq_data:
  cnd_rabbitmq_log:
  cnd_mongodb_data:

networks:
  cnd_network:
    driver: bridge