name: customer_service
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./customer_service
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r src/requirements.txt
      - 
        name: Test with pytest
        run: |
          python -c "import sys; print(sys.path)"
          python -m pytest test --cov=src
      - 
        name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_CND_TOKEN}}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and Push customer_service image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:customer_service"
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/customer_service:0.1.0
